{ name: 'ScheduleCall',
  description: null,
  slots: 
   [ { name: 'TimeZone',
       description: null,
       slotConstraint: 'Required',
       slotType: 'String',
       slotTypeVersion: '3',
       valueElicitationPrompt: [Object],
       priority: 5,
       sampleUtterances: [],
       responseCard: null },
     { name: 'Phone',
       description: null,
       slotConstraint: 'Required',
       slotType: 'AMAZON.PhoneNumber',
       slotTypeVersion: null,
       valueElicitationPrompt: [Object],
       priority: 6,
       sampleUtterances: [],
       responseCard: null },
     { name: 'Time',
       description: null,
       slotConstraint: 'Required',
       slotType: 'AMAZON.TIME',
       slotTypeVersion: null,
       valueElicitationPrompt: [Object],
       priority: 3,
       sampleUtterances: [],
       responseCard: null },
     { name: 'Date',
       description: null,
       slotConstraint: 'Required',
       slotType: 'AMAZON.DATE',
       slotTypeVersion: null,
       valueElicitationPrompt: [Object],
       priority: 2,
       sampleUtterances: [],
       responseCard: null } ],
  sampleUtterances: [ 'schedule a call', 'hi', 'yes' ],
  confirmationPrompt: { messages: [ [Object] ], maxAttempts: 3, responseCard: null },
  rejectionStatement: { messages: [ [Object] ], responseCard: null },
  fulfillmentActivity: { type: 'ReturnIntent' },
  parentIntentSignature: null,
  lastUpdatedDate: 2017-10-29T16:20:54.862Z,
  createdDate: 2017-10-16T14:58:02.150Z,
  version: '$LATEST',
  checksum: '4b63949c-7a67-43fb-b7db-7099a0ea851a' }
